### ISSUE TITLE
Absence of Lexical Senses

### ISSUE THREAD

**Issue by pedropaulofb** [sinaahmadi/KurdishLexicography#1]
Hi, I am trying to identify a well-structured ontolex-lemon lexicon and I came across your work. First of all, I would like to congratulate you on it. However, I have a doubt: each `Lexical Entry` have an `ontolex:sense` object property to an individual that is not declared as a `Lexical Sense`. The URI of these individuals seems also to be invalid. 

Can you please explain to me why there is no definition for them? Thank you in advance.

**Comment by sinaahmadi** [comment]
Hi @pedropaulofb ,
Thanks for raising the issue. 

You are right; unfortunately, the lexicographical data that was converted into Ontolex-Lemon was not complete making the conversion partially complete. This was the case for senses too as they were not described much (information such as glosses missing).

What is your task of interest for which you would need the data? I might have some ideas for you.

**Comment by pedropaulofb** [comment]
Hi @sinaahmadi, thanks for answering me!

I am working on an automated model-driven transformation for generating SKOS thesauri from Ontolex-Lemon lexicons (we named it Ontolex2SKOS. [Here is its repo](https://github.com/unibz-core/ontolex2skos) - sorry for the lack of documentation. 

It has been incredibly difficult to find an updated and complete lexicon for testing the tool. In most cases the download links are broken, the lexicons use an old version of Ontolex-Lemon (e.g., the one from the Monet project) or they do not have complete data. 

Do you know any lexicon that fits these criteria to inform me? I would really appreciate your help in this regard.

**Comment by sinaahmadi** [comment]
Cool! 
There are many out there, actually. For instance, Dbnary: http://kaiko.getalp.org/about-dbnary/online-access/ or Apertium: https://github.com/acoli-repo/acoli-dicts/tree/master/stable/apertium

If you are concerned with the data being complete for your tool to have all cases defined, I'd say working with a smaller dataset as a sample would make sense. Otherwise, it may not be easy to find something that uses all properties and vocabulary of Ontolex-Lemon at once!

**Comment by pedropaulofb** [comment]
Thank you very much for your contribution! I'll check both resources carefully and then I'll give you a return about them. =)

By the way, if you know more resources, please let me know.

**Comment by pedropaulofb** [comment]
@sinaahmadi, once again, thank you very much for the information! The Dbnary resources, with minor modifications, seem perfect for my tests!
